### ISSUE TITLE
RegexClassifier returns an error for Snort regexes

### ISSUE THREAD

**Issue by yotamhc** [DeepnessLab/obsi#19]
When trying to use RegexClassifier with all Snort regexes I still get an error in controller.

**Comment by yotamhc** [comment]
Seems like it has the same problem as HeaderClassifier with more than a certain amount of rules, this is the error Click produces given the config:

```
click: ../include/click/bitvector.hh:196: Bitvector::Bit Bitvector::operator[](int): Assertion `i >= 0 && i <= _max' failed.
```

**Comment by yotamhc** [comment]
When splitting regexes into multiple classifiers with up to 127 rules each, and removing illegal regexes (illegal with respect to RE2 rules), I still get an error that the DFA is too big:
re2/dfa.cc:469: DFA out of memory: prog size 86324 mem 3848788
/tmp/snort_obsi_run:21: While configuring ‘RegexClassifier_5_Snort@_@regex_classifier :: RegexClassifier’:
  unspecified error
re2/dfa.cc:454: DFA out of memory: prog size 476479 mem 2288168
/tmp/snort_obsi_run:23: While configuring ‘RegexClassifier_6_Snort@_@regex_classifier :: RegexClassifier’:
  unspecified error
re2/dfa.cc:454: DFA out of memory: prog size 261538 mem 3147932
/tmp/snort_obsi_run:25: While configuring ‘RegexClassifier_7_Snort@_@regex_classifier :: RegexClassifier’:
  unspecified error
Router could not be initialized!

This means that RE2 may not be suitable for network applications such as Snort...

**Comment by pavel-lazar** [comment]
RE2 allows to adjust the maximum memory per program (a DFA). Here is the
relevant part from the library (You have more experience with regex
implementations, so I will appreciate your input):
The max_mem option controls how much memory can be used to hold the
compiled form of the regexp (the Prog) and its cached DFA graphs. Code
Search placed limits on the number of Prog instructions and DFA states:
10,000 for both.

In RE2, those limits would translate to about 240 KB per Prog and perhaps
2.5 MB per DFA (DFA state sizes vary by regexp; RE2 does a better job of
keeping them small than Code Search did).
Each RE2 has two Progs (one forward, one reverse), and each Prog can have
two DFAs (one first match, one longest match).
That makes 4 DFAs:
forward, first-match - used for UNANCHORED or ANCHOR_LEFT searches if
opt.longest_match() == false

forward, longest-match - used for all ANCHOR_BOTH searches, and the other
two kinds if opt.longest_match() == true

reverse, first-match - never used

reverse, longest-match - used as second phase for unanchored searches

The RE2 memory budget is statically divided between the two Progs and then
the DFAs: two thirds to the forward Prog and one third to the reverse Prog.
The forward Prog gives half
of what it has left over to each of its DFAs. The reverse Prog gives it all
to its longest-match DFA.

Once a DFA fills its budget, it flushes its cache and starts over.
If this happens too often, RE2 falls back on the NFA implementation.

For now, make the default budget something close to Code Search.

**Comment by yotamhc** [comment]
This just explains how memory is divided, but do you have an idea how to simply increase the memory limit?
For the experiments I try to do I can use lots of memory. The machine has 384GB...

**Comment by pavel-lazar** [comment]
Oh, sorry. I forgot to mention that I can change that value. It is an
option I need to pass.

**Comment by yotamhc** [comment]
Can you make it really big? Or let me know how to?

I tried to give the RegexClassifier exact strings instead of regex. It works, but pretty slow... about 10Mbps...

**Comment by pavel-lazar** [comment]
The use of exect strings shouldn't make it slow. Did you use an alert or
log after a common match? RE2 should be really fast. The alert/log element
writes to a socket which can slow things down.

**Comment by yotamhc** [comment]
When I remove the alerts and immediately sends packets ToDevice after the RegexClassifier, throughput is about 15Mbps.
I expected to have throughput in orders of 100Mbps - 1Gbps...

But: for some reason I get an error from obsi when sending the processing graph, although if I take the dumped click config and give to click - it works.

**Comment by pavel-lazar** [comment]
And what throughput do you get when passing the config directly to click?

**Comment by yotamhc** [comment]
15Mbps. It doesn't work through obsi.

When I use less patterns (100 instead of a few thousands), thus I do not chain RegexClassifiers one after each other, I get about 200Mbps through OBSI with no errors.

**Comment by yotamhc** [comment]
I really need you to figure out this bitvector error in the classifiers when you have time... It seems to kill performance. I need to get reasonable experimental results as soon as possible.
