### ISSUE TITLE
OBSI returns error even when click succeeds loading config

### ISSUE THREAD

**Issue by yotamhc** [DeepnessLab/obsi#24]
In many cases, especially when the config is big, OBSI returns error (internal error) to controller for the SetProcessingGraphRequest.
Click is still running after this error message but it would not apply the new processing graph on packets.
However, if I take the config that is dumped to screen and give to click with -f, it works.

**Comment by yotamhc** [comment]
See OBSI run and error message:
[snort_run.zip](https://github.com/OpenBoxProject/obsi/files/102216/snort_run.zip)

**Comment by pavel-lazar** [comment]
Can you attach the JSON you send to OBSI?

**Comment by yotamhc** [comment]
[snort_request.zip](https://github.com/OpenBoxProject/obsi/files/104730/snort_request.zip)

**Comment by yotamhc** [comment]
After pulling recent code I get this error in controller after a few seconds from sending the SetProcessingGraphRequest:

INFO: Error sending message: 10001:Error:INTERNAL_ERROR:Timeout
  File "/home/yotam/obsi/openbox/message_router.py", line 42, in start
    yield handler(message)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(_exc_info)
  File "/home/yotam/obsi/openbox/message_handler.py", line 80, in handle_set_processing_graph_request
    yield self.manager.set_processing_graph(message.required_modules, message.blocks, message.connectors)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(_exc_info)
  File "./manager.py", line 415, in set_processing_graph
    yield client.fetch(uri, method='POST', body=json_encode(engine_config))
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info

The obsi console shows:
[W 160126 15:25:02 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:03 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:04 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:05 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:06 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:07 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:08 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:09 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:10 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:11 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:12 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:13 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:14 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:15 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:16 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:17 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:18 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:19 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:20 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:21 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:22 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:23 iostream:1186] Connect error on fd 10: ECONNREFUSED
[W 160126 15:25:24 iostream:1186] Connect error on fd 10: ECONNREFUSED
Traceback (most recent call last):
  File "/home/yotam/obsi/openbox/runner/rest_server.py", line 77, in <module>
Traceback (most recent call last):
  File "./manager.py", line 537, in <module>
    run(tornado.options.options.port, tornado.options.options.debug)
  File "/home/yotam/obsi/openbox/runner/rest_server.py", line 70, in run
    tornado.ioloop.IOLoop.current().start()
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 858, in start
    main()
  File "./manager.py", line 533, in main
    event_pairs = self._impl.poll(poll_timeout)

**Comment by yotamhc** [comment]
[snort_json.zip](https://github.com/OpenBoxProject/obsi/files/105156/snort_json.zip)

**Comment by yotamhc** [comment]
It still doesn't work on the server I use

**Comment by pavel-lazar** [comment]
I will check it out during the weekend. I will try to remove Click, pull it
apply my patch and hope for the best.

**Comment by yotamhc** [comment]
It seems that click takes very long time when configuring a classifier with several thousands of rules. This may be the reason that obsi eventually throws a timeout exception. Maybe the solution is to simply increase the timeout, or even only when the processing graph is large...

**Comment by pavel-lazar** [comment]
I couldn't reproduce in my setup, so I added a request timeout in the config.Manger. You can try and adjust is to a suitable value.
