### ISSUE TITLE
Some new fix makes OBSI not support hex values in HeaderClassifier match

### ISSUE THREAD

**Issue by yotamhc** [DeepnessLab/obsi#29]
Specifically I send 0x800 as ethtype and get an error. The error comes from line 34 where you do int(value) and value is '0x800' in this case.

**Comment by pavel-lazar** [comment]
Please attach a JSON with the message to reproduce the error.

**Comment by pavel-lazar** [comment]
It was never supported before(see the spec).

See new PR for support.

**Comment by yotamhc** [comment]
Oh sorry, so it just somehow worked before.
Thanks
